name: ci

on:
  push:
    branches: ["**"]
    paths:
      - "**/*.py"
      - "**/*.ipynb"
  pull_request:
    paths:
      - "**/*.py"
      - "**/*.ipynb"

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install project and tools
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pre-commit black

      - name: Black (check)
        run: |
          black --check .

      - name: Lint
        run: |
          make lint

      - name: Clean
        run: |
          make clean
