name: ci

on:
  push:
    branches: ["**"]
    paths:
      - "**/*.py"
      - "**/*.ipynb"
      - ".github/workflows/ci.yml"
      - "pyproject.toml"
  pull_request:
    paths:
      - "**/*.py"
      - "**/*.ipynb"
      - ".github/workflows/ci.yml"
      - "pyproject.toml"

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install project and tools
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pre-commit black ruff pytest

      - name: Black (check)
        run: |
          black --check .

      - name: Ruff (check)
        run: |
          ruff check . --output-format=github

      - name: Lint
        run: |
          make lint

      - name: Tests
        run: |
          pytest -q

      - name: Clean
        run: |
          make clean
