name: ci

on:
  push:
    branches: ["**"]
    paths:
      - "**/*.py"
      - "**/*.ipynb"
      - ".pre-commit-config.yaml"
      - "pyproject.toml"
      - "Makefile"
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - "**/*.py"
      - "**/*.ipynb"
      - ".pre-commit-config.yaml"
      - "pyproject.toml"
      - "Makefile"
      - ".github/workflows/ci.yml"
  workflow_dispatch:

concurrency:
  group: format-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            pyproject.toml
            .pre-commit-config.yaml

      - name: Install tools (no heavy project deps)
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit black isort flake8 nbqa

      - name: Black (check)
        run: black --check .

      - name: Lint (pre-commit over repo)
        run: make lint

      - name: Clean
        run: make clean
